name: TeisyokuPlugin2
version: 2.17.1
main: net.jp.minecraft.plugins.teisyokuplugin2.TeisyokuPlugin2
api-version: 1.15
commands:
    ad:
        description: Teisyoku Ad.
        usage: /ad <Messages>
    notice:
        description: Teisyoku Ad.
        usage: /notice <Messages>
    call:
        description: Teisyoku Call.
        usage: /call <Player> <Messages>
    cart:
        description: Give to Minecart.
        usage: /cart
    minecart:
        description: Give to Minecart.
        usage: /minecart
    color:
        description: color
        usage: /color
    daunii:
        discription: summon daunii
        usage: /daunii
    fly:
        description: Teisyoku Fly Command
        usage: /fly <Player> <true|false>
    teisyoku:
        description: teisyoku.
        usage: /teisyoku
    t:
        description: teisyoku.
        usage: /t
    players:
        description: show players list.
        usage: /players
    p:
        description: show players list.
        usage: /p
    nick:
        description: Nick
        usage: /nick
    nickname:
        description: Nickname
        usage: /nickname
    playerdata:
        description: show player date.
        usage: /playerdata <Player>
    pd:
        description: show player date.
        usage: /pd <Player>
    last:
        description: show player date.
        usage: /last <Player>
    point:
        description: TPoint
        usage: /point
    tpoint:
        description: TPoint
        usage: /tpoint
    tt:
        description: TPoint
        usage: /tpoint
    ri:
        description: RailwaysInfo
        usage: /ri
    railwaysinfo:
        description: RailwaysInfo
        usage: /railwaysinfo
    tabname:
        description: tabname
        usage: /tabname
    horse:
        description: horse
        usage: /horse
    carthelp:
        description: charthelp
        usage: /charthelp
    ch:
        description: charthelp
        usage: /charthelp
    gg:
        description: GoodGame
        usage: /gg
    bp:
        description: BaiPoint
        usage: /bp
    se:
        description: SignEdit
        usage: /se
    horseticket:
        discription: get ticket
        usage: /horseticket <zombie/skeleton> PlayerName
    ht:
        discription: get ticket
        usage: /ht <zombie/skeleton> PlayerName
    sign:
        discription: Sign Edit
        usage: /sign <String> <LineNo>
    tflag:
        discription: Teisyoku Flags
        usage: /tflag <flag> <value>
    trash:
        description: Gomibako.
        usage: /trash
    gomi:
        description: Gomibako.
        usage: /gomi
    gomibako:
        description: Gomibako.
        usage: /gomibako
permissions:
    teisyoku.*:
        description: Allow using TeisyokuPlugin2.
        default: op
    teisyoku.user:
        description: Teisyoku.
        default: true
    teisyoku.admin:
        description: Teisyoku admin
        default: op
    teisyoku.ad:
        description: Teisyoku ad command
        default: op
    teisyoku.ad.cooltime:
        description: Teisyoku ad command bypass cooltime
        default: op
    teisyoku.cart:
        description: Teisyoku cart command
        default: true
    teisyoku.cart.give:
        description: Teisyoku cart command
        default: op
    teisyoku.color:
        description: Teisyoku color command
        default: true
    teisyoku.daunii.use:
        description: Teisyoku daunii command
        default: true
    teisyoku.daunii.summon:
        description: Teisyoku daunii command
        default: op
    teisyoku.fly.me:
        description: Teisyoku fly command
        default: op
    teisyoku.fly.others:
        description: Teisyoku fly command
        default: op
    teisyoku.gift:
        description: Teisyoku gift command
        default: op
    teisyoku.horse:
        description: Teisyoku horse function
        default: true
    teisyoku.horse.admin:
        description: Teisyoku horse function
        default: op
    teisyoku.horse.bypass.ride:
        description: Teisyoku horse function
        default: op
    teisyoku.horse.bypass.damage:
        description: Teisyoku horse function
        default: op
    teisyoku.nickname:
        description: Teisyoku nickname command
        default: true
    teisyoku.playerdata:
        description: Teisyoku player data command
        default: true
    teisyoku.nickname.admin:
        description: Teisyoku nickname command
        default: op
    teisyoku.players:
        description: Teisyoku players command
        default: true
    teisyoku.railways:
        description: Teisyoku railways command
        default: true
    teisyoku.signedit:
        description: Teisyoku signedit command
        default: true
    teisyoku.tabname:
        description: Teisyoku tabname command
        default: op
    teisyoku.menu:
        description: Teisyoku menu function
        default: true
    teisyoku.tflag:
        description: Teisyoku tflag command
        default: true
    teisyoku.tflag.search:
        description: Teisyoku tflag command
        default: true
    teisyoku.tpoint:
        description: Teisyoku tpoint function
        default: true
    teisyoku.tpoint.admin:
        description: Teisyoku tpoint function
        default: op
    teisyoku.tps:
        description: Teisyoku tps command
        default: true
    teisyoku.trash:
        description: Teisyoku trash command
        default: true
    teisyoku.portal.bypass.end:
        description: Bypass end portal
        default: false
    teisyoku.portal.bypass.nether:
        description: Bypass nether portal
        default: false
    teisyoku.villager.bypass.damage:
        description: Teisyoku villager function
        default: op